exec(open("fix_trio.py").read().split("# ---- P152")[0])
P150=rd("work/P150_solid.brep"); P152=rd("work/P152_solid.brep"); P154=rd("work/P154_solid.brep")
a=TopTools_ListOfShape(); a.Append(P150); t=TopTools_ListOfShape(); t.Append(P152); t.Append(P154)
fu=BRepAlgoAPI_Fuse(); fu.SetArguments(a); fu.SetTools(t); fu.SetFuzzyValue(1e-5); fu.Build()
u=ShapeUpgrade_UnifySameDomain(fu.Shape(),True,True,True); u.Build(); r=u.Shape()
print("solids",count(r,TopAbs_SOLID),"| shells",count(r,TopAbs_SHELL),"| faces",count(r,TopAbs_FACE))
ex=TopExp_Explorer(r,TopAbs_SOLID)
while ex.More(): so=ex.Current(); print("  solid: volume %.1f valid %s self-int %d"%(vol(so),BRepCheck_Analyzer(so).IsValid(),si(so))); ex.Next()
print("sum of inputs %.1f"%(vol(P150)+vol(P152)+vol(P154)))
BRepTools.Write_s(r,"work/trio_fused.brep")
